### ISSUE TITLE
Add show lists to twitter feed

### ISSUE THREAD

**Issue by timvantilborgh** [peterdesmet/petridish#24]
Great template. Could it be possible to add the option to show a list in the twitter feed on the homepage instead of the tweets of a person.

**Comment by peterdesmet** [comment]
:+1: I'll see if this can be implemented with https://help.twitter.com/en/using-twitter/twitter-lists

**Comment by peterdesmet** [comment]
With the move of researchers to Mastodon, I'm not planning to add more support for Twitter features.

**Comment by timvantilborgh** [comment]
Totally understandable 😃
