### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by peterdesmet** [peterdesmet/petridish#5]
Currently getting:

```
ERROR `/favicon.ico' not found.
```

When running `jekyll serve`

**Comment by jocelynpender** [comment]
Hi Peter! How do you add a favicon when using the petridish template? I couldn't figure it out! It would be great if this were documented. Thanks!

**Comment by peterdesmet** [comment]
It should work by adding a `favicon.ico` in the root of the repository (like here https://github.com/inbo/oscibio/blob/main/favicon.ico), but will document this.

**Comment by jocelynpender** [comment]
That didn't work for [my site](https://github.com/atlantichabitatmodels/communityofpractice). I'll keep testing. Thanks for the help!

**Comment by jocelynpender** [comment]
I hope it's OK that I reused your lovely documentation that I came across :) Many thanks!

**Comment by jocelynpender** [comment]
Did a bunch of digging... still can't figure it out... Please let me know if you find any info on how to set this up, thanks!
My site: https://github.com/atlantichabitatmodels/communityofpractice

**Comment by jocelynpender** [comment]
> It should work by adding a `favicon.ico` in the root of the repository (like here https://github.com/inbo/oscibio/blob/main/favicon.ico), but will document this.

Hello! I've tried many things (e.g., editing config file, creating a head_custom.html file..) but I still haven't been able to get the favicon to show. The file exists in the root of the repository and is named `favicon.ico`. I think the problem might be to do with the base URL.. Any help resolving this would be much appreciated. I can provide more details on things I've tried if it would be helpful. My experience with jekyll is limited to GitHub pages, so I don't have anything running locally to test. Thanks!

**Comment by peterdesmet** [comment]
Yes, I think it is indeed related to the baseurl. I'll see if I can resolve it in Petridish.

**Comment by peterdesmet** [comment]
This should now be resolved in Petridish, but you will have to update your [link to the theme](https://github.com/atlantichabitatmodels/communityofpractice/blob/b6582151165d959521d1972a7483b1c9646d448f/_config.yml#L14) to point to the actively developed theme:

    remote_theme: peterdesmet/petridish

This isn't good practice though, because you're site might change when I update Petridish. If you can wait, I hope to release a `@2.0` soon, which will again be a stable version.

**Comment by jocelynpender** [comment]
Just a quick note that when I changed to the actively developed theme, the favicon renders, woohoo!! But a bunch of other things are broken, so I'll switch back to the previous release.
Let me know when `@2.0` comes out, thanks!

E.g., messed up header:
![image](https://user-images.githubusercontent.com/16246446/165769232-ac2ea6ec-1897-48ac-8f6e-a38980c487c2.png)

**Comment by jocelynpender** [comment]
Hooray! I linked to `remote_theme: peterdesmet/petridish@2.0` and everything looks great! Thank you!

**Comment by peterdesmet** [comment]
Nice! Glad you find it useful.

**Comment by damianooldoni** [comment]
👋  @peterdesmet! 
On my browser (Google Chrome) the favicon is not displayed.

<img src = "https://github.com/peterdesmet/petridish/assets/33662631/0e2ba409-26af-4509-a43c-1816f27c5820" width=50% height=50%>

Same occurrs on the website I have just started using `remote_theme: peterdesmet/petridish@3.0` in `_config.yml` (see https://github.com/damianooldoni/notes/blob/main/_config.yml#L17).

Do you have any idea why? No urgency at all.

**Comment by peterdesmet** [comment]
The reason it doesn't appear on https://peterdesmet.com/petridish is because I haven't corrected the setting for https on peterdesmet yet. It does appear on http://peterdesmet.com/petridish or https://peterdesmet.github.io/petridish

A favicon does appear on your https://damianooldoni.github.io/notes/ in my browser.

**Comment by damianooldoni** [comment]
Thanks @peterdesmet to check this. I find that the favicon on my site is displayed correctly while using Edge instead of a Chrome browser + DuckDuckGo Privay Essentials extension. Also, if I use Chrome with a different account (and no DuckDuckGo extension) the favicon appears correctly. So the extension is the problem.
